name: Docker Image CI for GHCR
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'kubernetes/**'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build and push the image
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GH_PAT }} ghcr.io

          REPO_NAME=electronic-e-commerce
          IMAGE=ghcr.io/harshpanchal18/$REPO_NAME

          docker build \
            -t $IMAGE:${{ github.sha }} \
            -t $IMAGE:latest . \
            --label "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

          docker logout ghcr.io

  # build-and-deploy:
  #   runs-on: self-hosted
  #   steps:
  #     - name: deploy on your cluster
  #       run: |
  #         kubectl --kubeconfig /Users/harsh/.kube/config apply \
  #                 -f /Users/harsh/actions-runner/_work/electronic-e-commerce/electronic-e-commerce/deployment.yml